name: audio_progress_bar
description: "An interpolated smooth progress builder for audio controllers"
version: 0.0.1
homepage: https://github.com/slashstar-co/audio_progress_bar
repository: https://github.com/slashstar-co/audio_progress_bar
issue_tracker: https://github.com/slashstar-co/audio_progress_bar/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  provider: ^6.1.2
  just_audio: ^0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.audio_progress_bar.audio_progress_bar
        pluginClass: AudioProgressBarPlugin
      ios:
        pluginClass: AudioProgressBarPlugin
      linux:
        pluginClass: AudioProgressBarPlugin
      macos:
        pluginClass: AudioProgressBarPlugin
      windows:
        pluginClass: AudioProgressBarPluginCApi
      web:
        pluginClass: AudioProgressBarWeb
        fileName: audio_progress_bar_web.dart